cd $HOME/run/framework/src/border/server
make ROrdAudit
make ROrdBack
make ROrdBackDeal
make ROrdCnt
make ROrdConfirm
make ROrdDelay
make ROrdDelay
make ROrdDispQry
make ROrdElt
make ROrdExcDeal
make ROrdFinQry
make ROrdHurryup
make ROrdOTQry
make ROrdPay
make ROrdRemove
make ROrdResume
make ROrdRunnQry
make ROrdSuspend
